USE master
GO

DROP DATABASE QLBH
GO

CREATE DATABASE QLBH
GO

USE QLBH
GO

CREATE TABLE THANHPHO
(
	MATP VARCHAR(10) NOT NULL,
	TENTHANHPHO NVARCHAR(50),	
	PRIMARY KEY(MATP)
)

GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50),
	GIOITINH nvarchar(5),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	DIENTHOAI CHAR(10),
	HINH NVARCHAR(500),
	PRIMARY KEY (MANV)
)

GO


CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) NOT NULL,
	TENSP NVARCHAR(50),
	DONVITINH NVARCHAR(50),
	DONGIA INT,
	HINH NVARCHAR(500),
	PRIMARY KEY(MASP)
)

GO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) NOT NULL,
	TENCTY NVARCHAR(50),
	DIACHI NVARCHAR(100),
	MATP VARCHAR(10),
	DIENTHOAI VARCHAR(10),
	PRIMARY KEY (MAKH)
)

CREATE TABLE HOADON
(
	MAHD VARCHAR(10) NOT NULL,
	MAKH VARCHAR(10),
	MANV VARCHAR(10),
	NGAYLAPHD DATE,
	NGAYNHANHANG DATE,
	PRIMARY KEY(MAHD)	
)

CREATE TABLE CHITIETHOADON
(
	MAHD VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SOLUONG INT,
	PRIMARY KEY (MAHD,MASP)
)

GO
--ADD FK
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_MATP_KH FOREIGN KEY(MATP) REFERENCES THANHPHO(MATP)

GO

ALTER TABLE HOADON ADD CONSTRAINT FK_MAKH_HD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

GO

ALTER TABLE HOADON ADD CONSTRAINT FK_MANV_HD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

GO

ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_MASP_CTHD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

GO

ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_MAHD_CTHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)

GO

