--SANPHAM
CREATE PROC sp_InsertSanPham(@maSP VARCHAR(10), @tenSP NVARCHAR(50), @donviTinh NVARCHAR(50), @donGia int, @hinh NVARCHAR(50))
AS
	INSERT INTO SANPHAM(MASP,TENSP,DONVITINH,DONGIA,HINH)
	VALUES (@maSP,@tenSP,@donviTinh,@donGia,@hinh)
GO

CREATE PROC sp_DeleteSanPham(@maSP VARCHAR(10)) 
AS 
	DELETE FROM SANPHAM WHERE SANPHAM.MASP = @maSP
GO

CREATE PROC sp_UpdateSanPham(@maSP VARCHAR(10), @tenSP NVARCHAR(50), @donviTinh NVARCHAR(50), @donGia int, @hinh NVARCHAR(50)) -- UPDATE
AS
	UPDATE SANPHAM
	SET
		TENSP = @tenSP,
		DONVITINH = @donviTinh,
		DONGIA = @donGia,
		HINH = @hinh
	WHERE SANPHAM.MASP = @maSP
GO

CREATE PROC sp_SelectAllSanPham -- SELECT ALL
AS
	SELECT * FROM SANPHAM
GO

CREATE PROC sp_SelectSanPhamByMaSP(@maSP VARCHAR(10)) -- SELECT BY MaSP
AS
	SELECT * FROM SANPHAM
	WHERE SANPHAM.MASP = @maSP
GO

--CHITIETHOADON
CREATE PROC sp_InsertChiTietHoaDon(@maHD VARCHAR(10), @maSP VARCHAR(10), @soLuong int)
AS
	INSERT INTO CHITIETHOADON(MAHD,MASP,SOLUONG)
	VALUES (@maHD,@maSP,@soLuong)
GO

CREATE PROC sp_DeleteChiTietHoaDon(@maHD VARCHAR(10)) 
AS 
	DELETE FROM CHITIETHOADON WHERE CHITIETHOADON.MAHD = @maHD
GO

CREATE PROC sp_UpdateChiTietHoaDon(@maHD VARCHAR(10), @maSP VARCHAR(10), @soLuong int) -- UPDATE
AS
	UPDATE CHITIETHOADON
	SET	SOLUONG = @soLuong
	WHERE CHITIETHOADON.MAHD = @maHD AND CHITIETHOADON.MASP = @maSP
GO

CREATE PROC sp_SelectAllChiTietHoaDon -- SELECT ALL
AS
	SELECT * FROM CHITIETHOADON
GO

--THANHPHO
CREATE PROC sp_InsertThanhPho(@maTP VARCHAR(10), @tenTP NVARCHAR(50))
AS
	INSERT INTO THANHPHO(MATP,TENTHANHPHO)
	VALUES (@maTP,@tenTP)
GO

CREATE PROC sp_DeleteThanhPho(@maTP VARCHAR(10)) 
AS 
	DELETE FROM THANHPHO WHERE THANHPHO.MATP = @maTP
GO

CREATE PROC sp_UpdateThanhPho(@maTP VARCHAR(10), @tenTP NVARCHAR(50)) -- UPDATE
AS
	UPDATE THANHPHO
	SET TENTHANHPHO = @tenTP
	WHERE THANHPHO.MATP = @maTP
GO

CREATE PROC sp_SelectAllThanhPho -- SELECT ALL
AS
	SELECT * FROM THANHPHO
GO


CREATE PROC sp_SelectTenThanhPho
AS 
	SELECT THANHPHO.MATP,KHACHHANG.MATP 
	FROM THANHPHO,KHACHHANG
	WHERE THANHPHO.MATP = KHACHHANG.MATP
GO
--KHACHHANG
CREATE PROC sp_InsertKhachHang(@maKH VARCHAR(10), @tenCty NVARCHAR(50),@diaChi NVARCHAR(50), @maTP VARCHAR(10), @dienThoai VARCHAR(10))
AS
	INSERT INTO KHACHHANG(MAKH,TENCTY,DIACHI,MATP,DIENTHOAI)
	VALUES (@maKH,@tenCty,@diaChi,@maTP,@dienThoai)
GO

CREATE PROC sp_DeleteKhachHang(@maKH VARCHAR(10)) 
AS 
	DELETE FROM KHACHHANG WHERE KHACHHANG.MAKH = @maKH
GO

CREATE PROC sp_UpdateKhachHang(@maKH VARCHAR(10), @tenCty NVARCHAR(50),@diaChi NVARCHAR(50), @maTP VARCHAR(10), @dienThoai VARCHAR(10)) -- UPDATE
AS
	UPDATE KHACHHANG
	SET 
		TENCTY = @tenCty,
		DIACHI = @diaChi,
		MATP = @maTP,
		DIENTHOAI = @dienThoai
	WHERE KHACHHANG.MAKH = @maKH
GO

CREATE PROC sp_SelectAllKhachHang -- SELECT ALL
AS
	SELECT * FROM KHACHHANG
GO

CREATE PROC sp_SelectKhachHangByMaKH(@maKH VARCHAR(10)) -- SELECT BY MaKH
AS
	SELECT * FROM KHACHHANG
	WHERE KHACHHANG.MAKH = @maKH
GO

--HOADON
CREATE PROC sp_InsertHoaDon(@maHD VARCHAR(10), @maKH VARCHAR(10), @maNV varchar(10), @ngayLapHD date,@ngayNhanHang date)
AS
	INSERT INTO HOADON(MAHD,MAKH,MANV,NGAYLAPHD,NGAYNHANHANG)
	VALUES (@maHD,@maKH,@maNV,@ngayLapHD,@ngayNhanHang)
GO

CREATE PROC sp_DeleteHoaDon(@maHD VARCHAR(10)) 
AS 
	DELETE FROM HOADON WHERE HOADON.MAHD = @maHD
GO

CREATE PROC sp_UpdateHoaDon(@maHD VARCHAR(10), @maKH VARCHAR(10), @maNV varchar(10), @ngayLapHD date,@ngayNhanHang date) -- UPDATE
AS
	UPDATE HOADON
	SET 
		MAKH = @maKH,
		MANV = @maNV,
		NGAYLAPHD = @ngayLapHD,
		NGAYNHANHANG = @ngayNhanHang
	WHERE HOADON.MAHD = @maHD
GO

CREATE PROC sp_SelectAllHoaDon -- SELECT ALL
AS
	SELECT * FROM HOADON
GO
--NHANVIEN
CREATE PROC sp_InsertNhanVien(@maNV VARCHAR(10), @hoTen NVARCHAR(50), @gioiTinh nvarchar(5), @ngaySinh date,@diaChi nvarchar(100),@dienThoai char(10), @hinh nvarchar(50))
AS
	INSERT INTO NHANVIEN(MANV,HOTEN,GIOITINH,NGAYSINH,DIACHI,DIENTHOAI,HINH)
	VALUES (@maNV,@hoTen,@gioiTinh,@ngaySinh,@diaChi,@dienThoai,@hinh)
GO

CREATE PROC sp_DeleteNhanVien(@maNV VARCHAR(10)) 
AS 
	DELETE FROM NHANVIEN WHERE NHANVIEN.MANV = @maNV
GO


CREATE PROC sp_UpdateNhanVien(@maNV VARCHAR(10), @hoTen NVARCHAR(50), @gioiTinh nvarchar(5), @ngaySinh date,@diaChi nvarchar(100),@dienThoai char(10), @hinh nvarchar(50)) -- UPDATE
AS
	UPDATE NHANVIEN
	SET 
		HOTEN = @hoTen,
		GIOITINH = @gioiTinh,
		NGAYSINH = @ngaySinh,
		DIACHI = @diaChi,
		DIENTHOAI = @dienThoai,
		HINH = @hinh
	WHERE NHANVIEN.MANV = @maNV
GO

CREATE PROC sp_SelectAllNhanVien -- SELECT ALL
AS
	SELECT * FROM NHANVIEN
GO

